### ISSUE TITLE
Add SSM Models to the Leaderboard (Mamba, StripedHyena)?

### ISSUE THREAD

**Issue by freckletonj** [lm-sys/lm-sys.github.io#56]
Is this the right place for a request like this? Apologies if not.

Structured State Space models are a new, possibly "post-transformer" architecture that confer significant speed benefits. There are several pretrained models I'm aware of:

Striped Hyena:
https://huggingface.co/togethercomputer/StripedHyena-Nous-7B
https://huggingface.co/togethercomputer/StripedHyena-Hessian-7B

Mamba:
https://huggingface.co/state-spaces/mamba-2.8b-slimpj

**Comment by merrymercy** [comment]
https://huggingface.co/spaces/lmsys/chatbot-arena-leaderboard/discussions/11#65a4e29da1ad2835094cf852
